# documentation: https://docs.hyperfy.io/
# slogan: A high-performance 3D metaverse platform using Three.js and React
# tags: metaverse,3d,threejs,react,gaming
# logo: svgs/hyperfy.svg
# port: 3000

version: '3.8'

services:
  app:
    image: howieduhzit/hyperfy-docker:main
    container_name: ${COOLIFY_APP_NAME:-hyperfy}
    restart: unless-stopped
    environment:
      - SERVICE_FQDN_APP=${SERVICE_FQDN_APP:-test.howieduhzit.best}
      - WORLD=${WORLD:-world}
      - PORT=${PORT:-3000}
      - JWT_SECRET=${SERVICE_PASSWORD_APP}
      - ADMIN_CODE=${SERVICE_PASSWORD_ADMIN}
      - SAVE_INTERVAL=60
      - PUBLIC_MAX_UPLOAD_SIZE=12
      - PUBLIC_WS_URL=${SERVICE_URL_WS:-${SERVICE_FQDN_APP}/ws}
      - PUBLIC_API_URL=${SERVICE_URL_API:-${SERVICE_FQDN_APP}/api}
      - PUBLIC_ASSETS_URL=${SERVICE_URL_ASSETS:-${SERVICE_FQDN_APP}/assets}
      - NODE_ENV=${NODE_ENV:-production}
    ports:
      - ${COOLIFY_PORT_80:-80}:80
      - ${COOLIFY_PORT_443:-443}:443
      - ${COOLIFY_PORT_3000:-3000}:3000
    volumes:
      - type: bind
        source: ${COOLIFY_VOLUME_DATA}
        target: /app/data
        is_directory: true
      - type: bind
        source: ${COOLIFY_VOLUME_ASSETS}
        target: /app/assets
        is_directory: true
      - type: bind
        source: ${COOLIFY_VOLUME_WORLD}
        target: /app/world
        is_directory: true
    networks:
      coolify-infra: {}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hyperfy.rule=Host(`${SERVICE_FQDN_APP}`)"
      - "traefik.http.routers.hyperfy.entryPoints=http"
      - "coolify.managed=true"
      - "coolify.type=application"

networks:
  coolify-infra:
    external: ${COOLIFY_NETWORK_EXTERNAL:-true}

volumes:
  data:
    name: ${COOLIFY_VOLUME_DATA}
    driver: local
  assets:
    name: ${COOLIFY_VOLUME_ASSETS}
    driver: local
  world:
    name: ${COOLIFY_VOLUME_WORLD}
    driver: local 