version: '3.8'

services:
  hyperfy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hyperfy
    restart: unless-stopped
    environment:.
      - SERVICE_FQDN_WS=/ws 
      - SERVICE_FQDN_API=/api
      - SERVICE_FQDN_ASSETS=/assets
      - NODE_ENV=production
      - PORT=3000
      - PUBLIC_WS_URL=$SERVICE_FQDN_HYPERFY/ws
      - PUBLIC_API_URL=$SERVICE_FQDN_HYPERFY/api 
      - PUBLIC_ASSETS_URL=$SERVICE_FQDN_HYPERFY/assets
      - ADMIN_CODE=${ADMIN_CODE:-admin}
      - JWT_SECRET=${JWT_SECRET:-hyper}
      - SAVE_INTERVAL=${SAVE_INTERVAL:-60}
      - WORLD=${WORLD:-world}
      - PUBLIC_MAX_UPLOAD_SIZE=${PUBLIC_MAX_UPLOAD_SIZE:-32}

    volumes:
      - type: bind
        source: /nvme/hyperfy/world
        target: /app/world
        is_directory: true
#      - type: bind
#        source: ./.env
#        target: /app/.env
#        content: |
#    labels:
#      - 'caddy_0.handle_path.0_reverse_proxy={{upstreams 3000}}'