version: '3.8'

services:
  hyperfy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hyperfy
    restart: unless-stopped
    environment:
      - SERVICE_FQDN_HYPERFY_3000
      - SERVICE_FQDN_WS=/ws
      - SERVICE_FQDN_API=/api
      - SERVICE_FQDN_ASSETS=/assets
      - ADMIN_CODE=${ADMIN_CODE:-admin}
      - JWT_SECRET=${JWT_SECRET:-hyper}
      - PORT=3000
      - SAVE_INTERVAL=${SAVE_INTERVAL:-60}
      - WORLD=${WORLD:-world}
      - PUBLIC_MAX_UPLOAD_SIZE=${PUBLIC_MAX_UPLOAD_SIZE:-32}
      - PUBLIC_WS_URL=$SERVICE_FQDN_WS
      - PUBLIC_API_URL=$SERVICE_FQDN_API
      - PUBLIC_ASSETS_URL=$SERVICE_FQDN_ASSETS

    volumes:
      - type: bind
        source: /nvme/hyperfy/world
        target: /app/world
        is_directory: true