services:
  hyperfy:
    image: howieduhzit/hyperfy:latest
    container_name: hyperfy
    restart: unless-stopped
    environment:
      - SERVICE_FQDN_HYPERFY_3000=/
      - JWT_SECRET=${JWT_SECRET:-hyper}
      - ADMIN_CODE=${ADMIN_CODE:-admin}
      - PORT=3000
      - SAVE_INTERVAL=${SAVE_INTERVAL:-60}
      - WORLD=${WORLD:-world}
      - PUBLIC_MAX_UPLOAD_SIZE=${PUBLIC_MAX_UPLOAD_SIZE:-32}
      - PUBLIC_WS_URL=${SERVICE_FQDN_HYPERFY}/ws
      - PUBLIC_API_URL=${SERVICE_FQDN_HYPERFY}/api
      - PUBLIC_ASSETS_URL=${SERVICE_FQDN_HYPERFY}/assets

    volumes:
      - type: bind
        source: ./world
        target: /app/world
        is_directory: true