# documentation: https://docs.hyperfy.io/
# slogan: A high-performance 3D metaverse platform using Three.js and React
# tags: metaverse,3d,threejs,react,gaming
# logo: svgs/hyperfy.svg
# port: 3000

version: '3.8'

services:
  app:
    image: howieduhzit/hyperfy-docker:main
    container_name: ${COOLIFY_APP_NAME:-hyperfy}
    restart: unless-stopped
    environment:
      - DOMAIN=${SERVICE_FQDN_APP}
      - WORLD=${WORLD:-world}
      - PORT=${PORT:-3000}
      - JWT_SECRET=${SERVICE_PASSWORD_APP}
      - ADMIN_CODE=${SERVICE_PASSWORD_ADMIN}
      - SAVE_INTERVAL=60
      - PUBLIC_MAX_UPLOAD_SIZE=12
      - PUBLIC_WS_URL=${SERVICE_URL_WS:-${SERVICE_FQDN_APP}/ws}
      - PUBLIC_API_URL=${SERVICE_URL_API:-${SERVICE_FQDN_APP}/api}
      - PUBLIC_ASSETS_URL=${SERVICE_URL_ASSETS:-${SERVICE_FQDN_APP}/assets}
      - NODE_ENV=${NODE_ENV:-production}
    ports:
      - ${COOLIFY_PORT_80:-80}:80
      - ${COOLIFY_PORT_443:-443}:443
      - ${COOLIFY_PORT_3000:-3000}:3000
    volumes:
      - ${COOLIFY_VOLUME_APP:-app_data}:/app/data
      - ${COOLIFY_VOLUME_ASSETS:-app_assets}:/app/assets
      - ${COOLIFY_VOLUME_WORLD:-hyperfy_world}:/app/world
    networks:
      coolify-infra: {}
    labels:
      com.docker.compose.project: ${COMPOSE_PROJECT_NAME}
      coolify.version: ${VERSION}
      coolify.managed: "true"
      coolify.deployment.timestamp: ${DEPLOYMENT_TIMESTAMP}

networks:
  coolify-infra:
    external: ${COOLIFY_NETWORK_EXTERNAL:-true}

volumes:
  app_data:
    name: ${COOLIFY_VOLUME_APP:-hyperfy_data}
    driver: local
  app_assets:
    name: ${COOLIFY_VOLUME_ASSETS:-hyperfy_assets}
    driver: local
  world:
    name: ${COOLIFY_VOLUME_WORLD:-hyperfy_world}
    driver: local 