version: '3.8'

services:
  hyperfy:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    container_name: hyperfy
    restart: unless-stopped
    environment:
      - SERVICE_FQDN_HYPERFY_3000
      - NODE_ENV=production
      - ADMIN_CODE=${ADMIN_CODE:-admin}
      - JWT_SECRET=${JWT_SECRET:-hyper}
      - PORT=${PORT:-3000}
      - SAVE_INTERVAL=${SAVE_INTERVAL:-60}
      - WORLD=${WORLD:-world}
      - PUBLIC_MAX_UPLOAD_SIZE=${PUBLIC_MAX_UPLOAD_SIZE:-32}
      - PUBLIC_WS_URL=${PUBLIC_WS_URL:-${SERVICE_FQDN_HYPERFY}:3000/ws}
      - PUBLIC_API_URL=${PUBLIC_API_URL:-${SERVICE_FQDN_HYPERFY}:3000/api}
      - PUBLIC_ASSETS_URL=${PUBLIC_ASSETS_URL:-${SERVICE_FQDN_HYPERFY}/assets}

    volumes:
      - type: bind
        source: /nvme/hyperfy/world
        target: /app/world
        is_directory: true
#      - type: bind
#        source: ./.env
#        target: /app/.env
#        content: |
#    labels:
#      - 'caddy_0.handle_path.0_reverse_proxy={{upstreams 3000}}'